version: '3.7'
volumes:
  postgres-data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=test
      - POSTGRES_HOST=postgres
    ports:
      - '3000:3000'
    volumes:
      - .:/code

  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=test
    volumes:
      - postgres-data:/var/lib/postgresql/data
